### ISSUE TITLE
Calling Hero does not run setup with node v17+

### ISSUE THREAD

**Issue by Copennin** [Azure-Samples/communication-services-web-calling-hero#145]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> On node versions 17 and 18, npm run setup does not 

### Any log messages given by the failure
> 
#Npm debug log
```
0 verbose cli /home/copennin/.nvm/versions/node/v17.9.1/bin/node /home/copennin/.nvm/versions/node/v17.9.1/bin/npm
1 info using npm@8.11.0
2 info using node@v17.9.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/home/copennin/.nvm/versions/node/v17.9.1/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 3ms
9 timing config:load:file:/mnt/c/Users/copennin/Code/Sandbox/communication-services-web-calling-hero/Server/.npmrc Completed in 0ms
10 timing config:load:project Completed in 58ms
11 timing config:load:file:/home/copennin/.npmrc Completed in 0ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/home/copennin/.nvm/versions/node/v17.9.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 3ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 86ms
19 timing npm:load:configload Completed in 86ms
20 timing npm:load:mkdirpcache Completed in 5ms
21 timing npm:load:mkdirplogs Completed in 2ms
22 verbose title npm install
23 verbose argv "install"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 6ms
26 timing npm:load:display Completed in 11ms
27 verbose logfile logs-max:10 dir:/home/copennin/.npm/_logs
28 verbose logfile /home/copennin/.npm/_logs/2022-06-22T23_45_27_778Z-debug-0.log
29 timing npm:load:logFile Completed in 13ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 122ms
33 timing arborist:ctor Completed in 2ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 2645ms
37 timing idealTree:userRequests Completed in 1ms
38 silly idealTree buildDeps
39 timing idealTree:#root Completed in 2ms
40 silly fetch manifest @typescript-eslint/parser@^5.0.0
41 timing arborist:ctor Completed in 0ms
42 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 12823ms (cache revalidated)
43 silly fetch manifest eslint@^6.0.0 || ^7.0.0 || ^8.0.0
44 http fetch GET 200 https://registry.npmjs.org/eslint 151ms (cache revalidated)
45 timing idealTree Completed in 15780ms
46 timing command:install Completed in 15839ms
47 verbose stack Error: could not resolve
47 verbose stack     at PlaceDep.failPeerConflict (/home/copennin/.nvm/versions/node/v17.9.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:549:25)
47 verbose stack     at PlaceDep.place (/home/copennin/.nvm/versions/node/v17.9.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:199:21)
47 verbose stack     at new PlaceDep (/home/copennin/.nvm/versions/node/v17.9.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
47 verbose stack     at /home/copennin/.nvm/versions/node/v17.9.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:990:31
47 verbose stack     at Array.map (<anonymous>)
47 verbose stack     at Arborist.[buildDepStep] (/home/copennin/.nvm/versions/node/v17.9.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:990:8)
47 verbose stack     at async Arborist.buildIdealTree (/home/copennin/.nvm/versions/node/v17.9.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
47 verbose stack     at async Promise.all (index 1)
47 verbose stack     at async Arborist.reify (/home/copennin/.nvm/versions/node/v17.9.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
47 verbose stack     at async Install.exec (/home/copennin/.nvm/versions/node/v17.9.1/lib/node_modules/npm/lib/commands/install.js:156:5)
48 verbose cwd /mnt/c/Users/copennin/Code/Sandbox/communication-services-web-calling-hero/Server
49 verbose Linux 5.10.102.1-microsoft-standard-WSL2
50 verbose node v17.9.1
51 verbose npm  v8.11.0
52 error code ERESOLVE
53 error ERESOLVE could not resolve
54 error
55 error While resolving: [1m@typescript-eslint/eslint-plugin[22m@[1m5.8.1[22m
55 error Found: [1m@typescript-eslint/parser[22m@[1m4.33.0[22m[2m[22m
55 error [2mnode_modules/@typescript-eslint/parser[22m
55 error   [33mdev[39m [1m@typescript-eslint/parser[22m@"[1m^4.12.0[22m" from the root project
55 error
55 error Could not resolve dependency:
55 error [35mpeer[39m [1m@typescript-eslint/parser[22m@"[1m^5.0.0[22m" from [1m@typescript-eslint/eslint-plugin[22m@[1m5.8.1[22m[2m[22m
55 error [2mnode_modules/@typescript-eslint/eslint-plugin[22m
55 error   [33mdev[39m [1m@typescript-eslint/eslint-plugin[22m@"[1m^5.8.1[22m" from the root project
55 error
55 error Conflicting peer dependency: [1m@typescript-eslint/parser[22m@[1m5.29.0[22m[2m[22m
55 error [2mnode_modules/@typescript-eslint/parser[22m
55 error   [35mpeer[39m [1m@typescript-eslint/parser[22m@"[1m^5.0.0[22m" from [1m@typescript-eslint/eslint-plugin[22m@[1m5.8.1[22m[2m[22m
55 error   [2mnode_modules/@typescript-eslint/eslint-plugin[22m
55 error     [33mdev[39m [1m@typescript-eslint/eslint-plugin[22m@"[1m^5.8.1[22m" from the root project
55 error
55 error Fix the upstream dependency conflict, or retry
55 error this command with --force, or --legacy-peer-deps
55 error to accept an incorrect (and potentially broken) dependency resolution.
55 error
55 error See /home/copennin/.npm/eresolve-report.txt for a full report.
56 verbose exit 1
57 timing npm Completed in 16324ms
58 verbose unfinished npm timer reify 1655941528224
59 verbose unfinished npm timer reify:loadTrees 1655941528271
60 verbose unfinished npm timer idealTree:buildDeps 1655941530922
61 verbose unfinished npm timer idealTree:node_modules/@typescript-eslint/eslint-plugin 1655941530928
62 verbose code 1
63 error A complete log of this run can be found in:
63 error     /home/copennin/.npm/_logs/2022-06-22T23_45_27_778Z-debug-0.log


# npm resolution error report

2022-06-22T23:45:44.074Z

While resolving: @typescript-eslint/eslint-plugin@5.8.1
Found: @typescript-eslint/parser@4.33.0
node_modules/@typescript-eslint/parser
  dev @typescript-eslint/parser@"^4.12.0" from the root project

Could not resolve dependency:
peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.8.1
node_modules/@typescript-eslint/eslint-plugin
  dev @typescript-eslint/eslint-plugin@"^5.8.1" from the root project

Conflicting peer dependency: @typescript-eslint/parser@5.29.0
node_modules/@typescript-eslint/parser
  peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.8.1
  node_modules/@typescript-eslint/eslint-plugin
    dev @typescript-eslint/eslint-plugin@"^5.8.1" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "edge": {
    "type": "peer",
    "name": "@typescript-eslint/parser",
    "spec": "^5.0.0",
    "error": "INVALID",
    "from": {
      "name": "@typescript-eslint/eslint-plugin",
      "version": "5.8.1",
      "location": "node_modules/@typescript-eslint/eslint-plugin",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "dev",
          "name": "@typescript-eslint/eslint-plugin",
          "spec": "^5.8.1",
          "from": {
            "location": "/mnt/c/Users/copennin/Code/Sandbox/communication-services-web-calling-hero/Server"
          }
        }
      ]
    }
  },
  "dep": {
    "name": "@typescript-eslint/parser",
    "version": "5.29.0",
    "whileInstalling": {
      "name": "@typescript-eslint/eslint-plugin",
      "version": "5.8.1",
      "path": "/mnt/c/Users/copennin/Code/Sandbox/communication-services-web-calling-hero/Server/node_modules/@typescript-eslint/eslint-plugin"
    },
    "location": "node_modules/@typescript-eslint/parser",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "peer",
        "name": "@typescript-eslint/parser",
        "spec": "^5.0.0",
        "error": "INVALID",
        "from": {
          "name": "@typescript-eslint/eslint-plugin",
          "version": "5.8.1",
          "location": "node_modules/@typescript-eslint/eslint-plugin",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "dev",
              "name": "@typescript-eslint/eslint-plugin",
              "spec": "^5.8.1",
              "from": {
                "location": "/mnt/c/Users/copennin/Code/Sandbox/communication-services-web-calling-hero/Server"
              }
            }
          ]
        }
      }
    ]
  },
  "current": {
    "name": "@typescript-eslint/parser",
    "version": "4.33.0",
    "location": "node_modules/@typescript-eslint/parser",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "dev",
        "name": "@typescript-eslint/parser",
        "spec": "^4.12.0",
        "from": {
          "location": "/mnt/c/Users/copennin/Code/Sandbox/communication-services-web-calling-hero/Server"
        }
      }
    ]
  },
  "peerConflict": {
    "current": {
      "name": "@typescript-eslint/parser",
      "version": "4.33.0",
      "location": "node_modules/@typescript-eslint/parser",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "dev",
          "name": "@typescript-eslint/parser",
          "spec": "^4.12.0",
          "from": {
            "location": "/mnt/c/Users/copennin/Code/Sandbox/communication-services-web-calling-hero/Server"
          }
        }
      ]
    },
    "peer": {
      "name": "@typescript-eslint/parser",
      "version": "5.29.0",
      "whileInstalling": {
        "name": "@typescript-eslint/eslint-plugin",
        "version": "5.8.1",
        "path": "/mnt/c/Users/copennin/Code/Sandbox/communication-services-web-calling-hero/Server/node_modules/@typescript-eslint/eslint-plugin"
      },
      "location": "node_modules/@typescript-eslint/parser",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "peer",
          "name": "@typescript-eslint/parser",
          "spec": "^5.0.0",
          "error": "INVALID",
          "from": {
            "name": "@typescript-eslint/eslint-plugin",
            "version": "5.8.1",
            "location": "node_modules/@typescript-eslint/eslint-plugin",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "dev",
                "name": "@typescript-eslint/eslint-plugin",
                "spec": "^5.8.1",
                "from": {
                  "location": "/mnt/c/Users/copennin/Code/Sandbox/communication-services-web-calling-hero/Server"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false,
  "isMine": true
}
```

### Expected/desired behavior
> npm run setup completes as expected

### OS and Version?
> Windows 10 and Ubuntu 20.04 WSL 5.10.102.1-microsoft-standard-WSL2 #1 SMP x86_64 GNU/Linux

### Versions
>These versions do not work:
07:21:47 copennin@Copennin-Work-SurfaceBook communication-services-web-calling-hero ±|main ✗|→ nvm list
        v17.9.1
        v18.2.0
        v18.3.0  

This node version works:
node -v
v14.19.3

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dmceachernmsft** [comment]
Thanks for raising the issue @Copennin! Taking a look on our end now. Will update you on what we find shortly. 

@Lowdown901 what version of node are you running? will attempt your version as well.

**Comment by anjulgarg** [comment]
Hi @Lowdown901 
We have updated the sample code to make it work with node versions 17+
Here is the merge PR https://github.com/Azure-Samples/communication-services-web-calling-hero/pull/147

However, there is an issue with Node versions 17 and higher that causes webpack builds to fail.
The issue as well as the fix is described here https://github.com/webpack/webpack/issues/14532

Let us know if this works for you.

**Comment by Copennin** [comment]
Nice work @anjulgarg. 

Able to ```npm run setup ``` now and app does run after ```export NODE_OPTIONS=--openssl-legacy-provider```

I think we can close the issue, just want to bring it to your attention that there are some ERESOLVE issues, but nothing that prevents what an end-user would be trying to achieve here. 

02:11:45 copennin@Copennin-Work-SurfaceBook communication-services-web-calling-hero ±|main|→ nvm use 18
Now using node v18.3.0 (npm v8.11.0)
02:11:56 copennin@Copennin-Work-SurfaceBook communication-services-web-calling-hero ±|main|→ npm run setup

> communication-services-web-calling-hero@1.0.0 setup
> cd Server && npm install && cd ../Calling && npm install && cd ..

npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

added 972 packages, and audited 973 packages in 36s

107 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-aria-live@2.0.5
npm WARN Found: react@17.0.0
npm WARN node_modules/react
npm WARN   react@"17.0.0" from the root project
npm WARN   34 more (@azure/communication-react, @fluentui/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.3.x" from react-aria-live@2.0.5
npm WARN node_modules/react-aria-live
npm WARN   react-aria-live@"^2.0.5" from @azure/communication-react@1.2.0
npm WARN   node_modules/@azure/communication-react
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.3.x" from react-aria-live@2.0.5
npm WARN   node_modules/react-aria-live
npm WARN     react-aria-live@"^2.0.5" from @azure/communication-react@1.2.0
npm WARN     node_modules/@azure/communication-react
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-fela@10.8.2
npm WARN Found: react@17.0.0
npm WARN node_modules/react
npm WARN   react@"17.0.0" from the root project
npm WARN   34 more (@azure/communication-react, @fluentui/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.3.0" from react-fela@10.8.2
npm WARN node_modules/react-fela
npm WARN   react-fela@"^10.6.1" from @fluentui/react-northstar-fela-renderer@0.61.0
npm WARN   node_modules/@fluentui/react-northstar-fela-renderer
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.3.0" from react-fela@10.8.2
npm WARN   node_modules/react-fela
npm WARN     react-fela@"^10.6.1" from @fluentui/react-northstar-fela-renderer@0.61.0
npm WARN     node_modules/@fluentui/react-northstar-fela-renderer
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1

added 1579 packages, and audited 1580 packages in 2m

142 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
02:14:53 copennin@Copennin-Work-SurfaceBook communication-services-web-calling-hero ±|main|→ npm run start

> communication-services-web-calling-hero@1.0.0 start
> cd Calling && npm run start && cd ..


> calling@0.0.1 start
> concurrently "cd ../Server && npm run start:dev" "npm run start:app"

[0] 
[0] > server@0.0.1 start:dev
[0] > ts-node-dev ./bin/www
[0] 
[1] 
[1] > calling@0.0.1 start:app
[1] > webpack-cli serve --mode=development --env development
[1] 
[0] [INFO] 14:15:14 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.3.5)
[1] <i> [webpack-dev-server] [HPM] Proxy created: /token  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /refreshToken/*  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /isValidThread/*  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /createThread  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /userConfig/*  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /getEndpointUrl  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /addUser/*  -> http://[::1]:8080
[1] <i> [webpack-dev-server] Project is running at:
[1] <i> [webpack-dev-server] Loopback: http://localhost:3000/
[1] <i> [webpack-dev-server] On Your Network (IPv4): http://172.26.176.76:3000/
[1] <i> [webpack-dev-server] Content not from webpack is served from '/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/public' directory
[1] Error: error:0308010C:digital envelope routines::unsupported
[1]     at new Hash (node:internal/crypto/hash:67:19)
[1]     at Object.createHash (node:crypto:133:10)
[1]     at BulkUpdateDecorator.hashFactory (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/util/createHash.js:145:18)
[1]     at BulkUpdateDecorator.update (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/util/createHash.js:46:50)
[1]     at OriginalSource.updateHash (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
[1]     at NormalModule._initBuildHash (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:870:17)
[1]     at handleParseResult (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:936:10)
[1]     at /home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:1028:4
[1]     at processResult (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:745:11)
[1]     at /home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:809:5
[1] node:internal/crypto/hash:67
[1]   this[kHandle] = new _Hash(algorithm, xofLen);
[1]                   ^
[1] 
[1] Error: error:0308010C:digital envelope routines::unsupported
[1]     at new Hash (node:internal/crypto/hash:67:19)
[1]     at Object.createHash (node:crypto:133:10)
[1]     at BulkUpdateDecorator.hashFactory (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/util/createHash.js:145:18)
[1]     at BulkUpdateDecorator.update (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/util/createHash.js:46:50)
[1]     at OriginalSource.updateHash (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
[1]     at NormalModule._initBuildHash (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:870:17)
[1]     at handleParseResult (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:936:10)
[1]     at /home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:1028:4
[1]     at processResult (/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:745:11)
[1]     at /home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/node_modules/webpack/lib/NormalModule.js:809:5 {
[1]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[1]   library: 'digital envelope routines',
[1]   reason: 'unsupported',
[1]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[1] }
[1] 
[1] Node.js v18.3.0
[1] npm run start:app exited with code 1
[0] Express server started (http://localhost:8080).
^C[0] cd ../Server && npm run start:dev exited with code SIGINT

02:15:57 copennin@Copennin-Work-SurfaceBook communication-services-web-calling-hero ±|main|→ export NODE_OPTIONS=--openssl-legacy-provider
02:16:00 copennin@Copennin-Work-SurfaceBook communication-services-web-calling-hero ±|main|→ npm run start

> communication-services-web-calling-hero@1.0.0 start
> cd Calling && npm run start && cd ..


> calling@0.0.1 start
> concurrently "cd ../Server && npm run start:dev" "npm run start:app"

[0] 
[0] > server@0.0.1 start:dev
[0] > ts-node-dev ./bin/www
[0] 
[1] 
[1] > calling@0.0.1 start:app
[1] > webpack-cli serve --mode=development --env development
[1] 
[0] [INFO] 14:16:08 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.3.5)
[1] <i> [webpack-dev-server] [HPM] Proxy created: /token  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /refreshToken/*  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /isValidThread/*  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /createThread  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /userConfig/*  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /getEndpointUrl  -> http://[::1]:8080
[1] <i> [webpack-dev-server] [HPM] Proxy created: /addUser/*  -> http://[::1]:8080
[1] <i> [webpack-dev-server] Project is running at:
[1] <i> [webpack-dev-server] Loopback: http://localhost:3000/
[1] <i> [webpack-dev-server] On Your Network (IPv4): http://172.26.176.76:3000/
[1] <i> [webpack-dev-server] Content not from webpack is served from '/home/copennin/Code/ACS/communication-services-web-calling-hero/Calling/public' directory
[1] <i> [webpack-dev-middleware] wait until bundle finished: /
[0] Express server started (http://localhost:8080).
[1] asset build.js 23.7 MiB [emitted] (name: main)
[1] asset index.html 601 bytes [emitted]
[1] orphan modules 15.7 MiB [orphan] 11817 modules
[1] runtime modules 27.9 KiB 15 modules
[1] cacheable modules 7.99 MiB
[1]   javascript modules 7.87 MiB
[1]     modules by path ./node_modules/ 7.84 MiB 1448 modules
[1]     modules by path ./src/ 35.6 KiB
[1]       modules by path ./src/app/ 32 KiB 15 modules
[1]       modules by path ./src/*.css 3.08 KiB
[1]         ./src/index.css 1.32 KiB [built] [code generated]
[1]         ./node_modules/css-loader/dist/cjs.js!./src/index.css 1.77 KiB [built] [code generated]
[1]       ./src/index.tsx 513 bytes [built] [code generated]
[1]   json modules 117 KiB
[1]     modules by path ./node_modules/@azure/communication-react/dist/dist-esm/react-components/src/ 73.6 KiB 14 modules
[1]     modules by path ./node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/ 43.4 KiB 14 modules
[1]   ./src/assets/hero.svg 8.28 KiB [built] [code generated]
[1] webpack 5.38.1 compiled successfully in 59502 ms
[0] Error: Invalid connection string REPLACE_WITH_CONNECTION_STRING
[0]     at parseConnectionString (/home/copennin/Code/ACS/communication-services-web-calling-hero/Server/node_modules/@azure/communication-common/src/credential/connectionString.ts:43:11)
[0]     at Object.parseClientArguments (/home/copennin/Code/ACS/communication-services-web-calling-hero/Server/node_modules/@azure/communication-common/src/credential/clientArguments.ts:63:44)
[0]     at new CommunicationIdentityClient (/home/copennin/Code/ACS/communication-services-web-calling-hero/Server/node_modules/@azure/communication-identity/src/communicationIdentityClient.ts:79:33)
[0]     at getIdentityClient (/home/copennin/Code/ACS/communication-services-web-calling-hero/Server/src/lib/identityClient.ts:17:39)
[0]     at Object.createUserAndToken (/home/copennin/Code/ACS/communication-services-web-calling-hero/Server/src/lib/identityClient.ts:27:3)
[0]     at /home/copennin/Code/ACS/communication-services-web-calling-hero/Server/src/routes/issueToken.ts:16:16
[0]     at Generator.next (<anonymous>)
[0]     at /home/copennin/Code/ACS/communication-services-web-calling-hero/Server/src/routes/issueToken.ts:29:71
[0]     at new Promise (<anonymous>)
[0]     at __awaiter (/home/copennin/Code/ACS/communication-services-web-calling-hero/Server/src/routes/issueToken.ts:25:12)
[0] [ERROR] 14:17:25 Error: Invalid connection string REPLACE_WITH_CONNECTION_STRING
[1] <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:3000/token?scope=voip to http://[::1]:8080/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)

Thanks, again.

**Comment by Lowdown901** [comment]
My Node version was 18.2.0
